version: '3.6'

volumes:
  wordpress:
  wordpress_db:

services:
  db:
    container_name: wordpress-db
    image: mysql:5.7
    env_file: .env
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - wp-network

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress:/var/www/html
      - ./woocommerce-gateway-wompi:/var/www/html/wp-content/plugins/woocommerce-gateway-wompi
    networks:
      - wp-network

  # wpcli:
  #   container_name: wordpress-cli
  #   image: wordpress:cli
  #   env_file: .env
  #   depends_on:
  #     - db
  #     - wordpress
  #   user: xfs
  #   environment:
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #     - wp-network
  #   command: /bin/sh -c '
  #     sleep 30;
  #     wp plugin install woocommerce && wp plugin activate woocommerce;
  #     tail -f /dev/null
  #     '

networks:
  wp-network:
    driver: bridge
